# Generated by Django 5.2.1 on 2025-06-10 22:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('gérant', 'Gérant'), ('client', 'Client')], max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$')])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/utilisateurs/')),
                ('mot_de_passe', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Atelier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/ateliers/')),
                ('utilisateur', models.OneToOneField(limit_choices_to={'role': 'gérant'}, on_delete=django.db.models.deletion.CASCADE, to='acceil.utilisateur')),
            ],
        ),
    ]
