# Generated by Django 5.2.1 on 2025-06-10 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acceil', '0002_rename_nom_atelier'),
    ]

    operations = [
    ]
