# Generated by Django 5.2.1 on 2025-06-11 07:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceil', '0003_auto_20250611_0148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atelier',
            options={'verbose_name': 'Atelier', 'verbose_name_plural': 'Ateliers'},
        ),
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.RemoveField(
            model_name='atelier',
            name='photo',
        ),
        migrations.AddField(
            model_name='atelier',
            name='photo_atelier',
            field=models.ImageField(blank=True, null=True, upload_to='photos/ateliers/', verbose_name="Photo de l'atelier"),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='adresse',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5, message="L'adresse doit contenir au moins 5 caractères")], verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(50, message='La description doit contenir au moins 50 caractères')], verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='nom_atelier',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, message="Le nom de l'atelier doit contenir au moins 3 caractères")], verbose_name="Nom de l'atelier"),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='utilisateur',
            field=models.OneToOneField(limit_choices_to={'role': 'gérant'}, on_delete=django.db.models.deletion.CASCADE, related_name='atelier', to='acceil.utilisateur'),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='ville',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, message='Le nom de la ville doit contenir au moins 2 caractères')], verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Cette adresse email est déjà utilisée.'}, max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='prenom',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('gérant', 'Gérant'), ('client', 'Client')], default='client', max_length=20),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$', message='Format de téléphone invalide')], verbose_name='Téléphone'),
        ),
    ]
