# Generated by Django 5.2.3 on 2025-06-11 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acceil', '0004_alter_atelier_options_alter_utilisateur_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('tour_poitrine', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Tour de poitrine (cm)')),
                ('tour_taille', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Tour de taille (cm)')),
                ('tour_hanches', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Tour de hanches (cm)')),
                ('longueur_epaule', models.DecimalField(decimal_places=1, max_digits=5, verbose_name="Longueur d'épaule (cm)")),
                ('hauteur_epaule', models.DecimalField(decimal_places=1, max_digits=5, verbose_name="Hauteur d'épaule (cm)")),
                ('longueur_buste', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Longueur du buste (cm)')),
                ('longueur_bras', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Longueur de bras (cm)')),
                ('tour_biceps', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Tour de biceps (cm)')),
                ('tour_poignet', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Tour de poignet (cm)')),
                ('longueur_epaule_coude', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Longueur épaule à coude (cm)')),
                ('longueur_jambe', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Longueur de jambe (cm)')),
                ('entrejambe', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Entrejambe (cm)')),
                ('tour_cuisse', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Tour de cuisse (cm)')),
                ('tour_genou', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Tour de genou (cm)')),
                ('tour_mollet', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Tour de mollet (cm)')),
                ('tour_cheville', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Tour de cheville (cm)')),
                ('tour_cou', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Tour de cou (cm)')),
                ('hauteur_dos', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Hauteur du dos (cm)')),
                ('carrure_dos', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Carrure du dos (cm)')),
                ('largeur_epaules', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Largeur des épaules (cm)')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='acceil.utilisateur')),
            ],
            options={
                'verbose_name': 'Mesure',
                'verbose_name_plural': 'Mesures',
                'ordering': ['-date_modification'],
            },
        ),
    ]
