# Generated by Django 5.2.3 on 2025-06-14 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acceil', '0004_alter_atelier_options_alter_utilisateur_options_and_more'),
        ('atelier', '0005_merge_20250613_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, editable=False, max_length=100, unique=True, verbose_name='Référence')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_echeance', models.DateField(help_text='Date limite de livraison', verbose_name="Date d'échéance")),
                ('status', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('en_attente', 'En attente'), ('recupere', 'Récupérée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('atelier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commandes_atelier', to='acceil.atelier', verbose_name='Atelier')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commandes_client', to='acceil.utilisateur', verbose_name='Client')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commandes_produit', to='atelier.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_creation'],
            },
        ),
    ]
