# Generated by Django 5.2.3 on 2025-06-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0002_alter_commande_date_echeance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_echeance',
            field=models.DateField(blank=True, help_text='Date limite de livraison (définie par le gérant)', null=True, verbose_name="Date d'échéance"),
        ),
    ]
