"""
Django settings for couture project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import pymysql
pymysql.install_as_MySQLdb()

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@01t*=)ybt(zhv4adsjbypv*eeso6y4ti78uqxviiz+&3!i2yf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']
# ALLOWED_HOSTS = ['una.theses.ci','houessou.theses.ci']



# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Ajout de jazzmin avant django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Applications personnalisées
    'acceil',
    'administration',
    'atelier',
    'commande',
    'utilisateur',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'couture.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'couture.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'couture_db',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}



# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# EN PRODUCTION
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'sc5zds_bd_couture',
#         'USER': 'sc5zds_houessou',
#
#         'PASSWORD': '%zP342TC$#ep',
#         'HOST': 'localhost',
#         'PORT': '3306',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Configuration pour les fichiers médias
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Configuration de WhiteNoise pour les fichiers statiques
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Ajout de la configuration pour servir les fichiers médias en production
if not DEBUG:
    # Configuration pour servir les fichiers médias via le serveur web
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'
    
    # Configuration pour les fichiers statiques
    STATIC_URL = '/static/'
    STATIC_ROOT = BASE_DIR / 'staticfiles'
    
   

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuration d'authentification
LOGIN_URL = '/acceil/connexion/'
LOGIN_REDIRECT_URL = '/administration/orders/'

# Configuration de Jazzmin
JAZZMIN_SETTINGS = {
    # Titre de la page d'administration
    "site_title": "Atelier de Couture",
    "site_header": "Atelier de Couture",
    "site_brand": "Atelier de Couture",
    "welcome_sign": "Bienvenue dans l'administration",
    "copyright": "Atelier de Couture",
    "search_model": ["atelier.Atelier", "commande.Commande"],
    
    # Thème et style
    "theme": "default",
    "dark_mode_theme": "darkly",
    "show_ui_builder": True,
    
    # Icônes personnalisées
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "atelier.Atelier": "fas fa-store",
        "atelier.Produit": "fas fa-tshirt",
        "atelier.Photo": "fas fa-camera",
        "commande.Commande": "fas fa-shopping-cart",
        "commande.RendezVous": "fas fa-calendar-alt",
        "commande.Mesure": "fas fa-ruler",
        "utilisateur.Client": "fas fa-user",
        "utilisateur.Gerant": "fas fa-user-tie",
    },
    
    # Menu personnalisé
    "order_with_respect_to": ["auth", "atelier", "commande", "utilisateur"],
    "custom_links": {
        "atelier": [{
            "name": "Statistiques", 
            "url": "admin:atelier_statistics",
            "icon": "fas fa-chart-bar",
        }],
        "commande": [{
            "name": "Rapports", 
            "url": "admin:commande_reports",
            "icon": "fas fa-file-alt",
        }],
    },
    
    # Personnalisation de l'interface
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    
    # En-tête personnalisé
    "topmenu_links": [
        {"name": "Accueil", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Site", "url": "/", "new_window": True},
        {"name": "Support", "url": "/contact", "new_window": True},
    ],
    
    # Pied de page personnalisé
    "footer_text": "© 2024 Atelier de Couture - Tous droits réservés",
    
    # Couleurs personnalisées
    "brand_colors": {
        "primary": "#EC9712",
        "secondary": "#2c3e50",
        "accent": "#EC9712",
        "success": "#28a745",
        "info": "#17a2b8",
        "warning": "#EC9712",
        "danger": "#dc3545",
    },
    
    # Personnalisation des listes
    "list_per_page": 25,
    "list_max_show_all": 100,
    
    # Personnalisation des formulaires
    "form_size": "large",
    "form_show_labels": True,
    
    # Personnalisation des actions
    "actions_sticky_top": True,
    "actions_on_top": True,
    "actions_on_bottom": True,
    
    # Personnalisation des filtres
    "filter_horizontal": True,
    "filter_vertical": True,
    
    # Personnalisation des messages
    "message_style": "toast",
    "message_position": "top-right",
    
    # Personnalisation des onglets
    "tab_size": "large",
    "tab_style": "pills",
    
    # Personnalisation des boutons
    "button_style": "rounded",
    "button_size": "large",
    
    # Personnalisation des cartes
    "card_style": "outlined",
    "card_size": "large",
    
    # Personnalisation des tableaux
    "table_style": "striped",
    "table_size": "large",
    
    # Personnalisation des alertes
    "alert_style": "toast",
    "alert_position": "top-right",
    
    # Personnalisation des modales
    "modal_style": "centered",
    "modal_size": "large",
    
    # Personnalisation des tooltips
    "tooltip_style": "light",
    "tooltip_position": "top",
    
    # Personnalisation des popovers
    "popover_style": "light",
    "popover_position": "top",
    
    # Personnalisation des badges
    "badge_style": "pill",
    "badge_size": "large",
    
    # Personnalisation des progress bars
    "progress_style": "striped",
    "progress_size": "large",
    
    # Personnalisation des spinners
    "spinner_style": "border",
    "spinner_size": "large",
    
    # Personnalisation des paginations
    "pagination_style": "rounded",
    "pagination_size": "large",
    
    # Personnalisation des breadcrumbs
    "breadcrumb_style": "rounded",
    "breadcrumb_size": "large",
    
    # Personnalisation des navbars
    "navbar_style": "light",
    "navbar_size": "large",
    
    # Personnalisation des sidebars
    "sidebar_style": "light",
    "sidebar_size": "large",
    
    # Personnalisation des footers
    "footer_style": "light",
    "footer_size": "large",

    "login_logo": "static/acceil/img/logo.png",
    "login_logo_dark": "static/acceil/img/logo.png",
    "site_logo": "static/acceil/img/logo.png",
    "site_icon": "static/acceil/img/favicon.ico",
    "login_background": "static/acceil/img/bg_connexion.jpg",
    "login_title": "Bienvenue sur l'administration Atelier de Couture",
    "login_message": "Connectez-vous pour accéder à votre espace de gestion.",
    "login_form_border_color": "#EC9712",
    "login_button_class": "btn-warning",
}

# Configuration des messages et de l'interface
JAZZMIN_UI_TWEAKS = {
    # Personnalisation de la barre de navigation
    "navbar_small_text": False,
    "navbar_fixed": True,
    "navbar_nav_small_text": False,
    "navbar_dropdown_small_text": False,
    "navbar_brand_small_text": False,
    "navbar_brand_colour": "navbar-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    
    # Personnalisation du pied de page
    "footer_small_text": False,
    "footer_fixed": False,
    "footer_colour": "footer-light",
    
    # Personnalisation du corps
    "body_small_text": False,
    "body_colour": "body-light",
    
    # Personnalisation de la marque
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    
    # Personnalisation des accents
    "accent": "accent-primary",
    "accent_small_text": False,
    
    # Personnalisation de la mise en page
    "layout_boxed": False,
    "layout_fixed": True,
    "layout_navbar_fixed": True,
    "layout_footer_fixed": False,
    "layout_sidebar_fixed": True,
    
    # Personnalisation de la barre latérale
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    
    # Personnalisation des thèmes
    "theme": "default",
    "dark_mode_theme": "darkly",
    
    # Personnalisation des boutons
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    
    # Personnalisation des cartes
    "card_classes": {
        "primary": "card-primary",
        "secondary": "card-secondary",
        "info": "card-info",
        "warning": "card-warning",
        "danger": "card-danger",
        "success": "card-success"
    },
    
    # Personnalisation des alertes
    "alert_classes": {
        "primary": "alert-primary",
        "secondary": "alert-secondary",
        "info": "alert-info",
        "warning": "alert-warning",
        "danger": "alert-danger",
        "success": "alert-success"
    },
    
    # Personnalisation des badges
    "badge_classes": {
        "primary": "badge-primary",
        "secondary": "badge-secondary",
        "info": "badge-info",
        "warning": "badge-warning",
        "danger": "badge-danger",
        "success": "badge-success"
    },
    
    # Personnalisation des progress bars
    "progress_classes": {
        "primary": "progress-primary",
        "secondary": "progress-secondary",
        "info": "progress-info",
        "warning": "progress-warning",
        "danger": "progress-danger",
        "success": "progress-success"
    },
    
    # Personnalisation des spinners
    "spinner_classes": {
        "primary": "spinner-primary",
        "secondary": "spinner-secondary",
        "info": "spinner-info",
        "warning": "spinner-warning",
        "danger": "spinner-danger",
        "success": "spinner-success"
    },
    
    # Personnalisation des paginations
    "pagination_classes": {
        "primary": "pagination-primary",
        "secondary": "pagination-secondary",
        "info": "pagination-info",
        "warning": "pagination-warning",
        "danger": "pagination-danger",
        "success": "pagination-success"
    },
    
    # Personnalisation des breadcrumbs
    "breadcrumb_classes": {
        "primary": "breadcrumb-primary",
        "secondary": "breadcrumb-secondary",
        "info": "breadcrumb-info",
        "warning": "breadcrumb-warning",
        "danger": "breadcrumb-danger",
        "success": "breadcrumb-success"
    },
    
    # Personnalisation des navbars
    "navbar_classes": {
        "primary": "navbar-primary",
        "secondary": "navbar-secondary",
        "info": "navbar-info",
        "warning": "navbar-warning",
        "danger": "navbar-danger",
        "success": "navbar-success"
    },
    
    # Personnalisation des sidebars
    "sidebar_classes": {
        "primary": "sidebar-primary",
        "secondary": "sidebar-secondary",
        "info": "sidebar-info",
        "warning": "sidebar-warning",
        "danger": "sidebar-danger",
        "success": "sidebar-success"
    },
    
    # Personnalisation des footers
    "footer_classes": {
        "primary": "footer-primary",
        "secondary": "footer-secondary",
        "info": "footer-info",
        "warning": "footer-warning",
        "danger": "footer-danger",
        "success": "footer-success"
    }
}
