# Generated by Django 5.2.1 on 2025-06-11 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acceil', '0004_alter_atelier_options_alter_utilisateur_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/galerie/')),
                ('titre', models.CharField(blank=True, max_length=100)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('atelier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='acceil.atelier')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('categorie', models.CharField(choices=[('femmes', 'Femmes'), ('hommes', 'Hommes'), ('enfants', 'Enfants')], max_length=20)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/produits/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('atelier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='acceil.atelier')),
            ],
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=15)),
                ('service', models.CharField(choices=[('retouches', 'Retouches'), ('sur-mesure', 'Création sur-mesure'), ('broderie', 'Broderie'), ('conseil', 'Conseil/Devis')], max_length=20)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('message', models.TextField(blank=True)),
                ('confirme', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('atelier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='acceil.atelier')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prix_minimum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('atelier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='acceil.atelier')),
            ],
        ),
    ]
