# Generated by Django 5.2.3 on 2025-06-13 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceil', '0004_alter_atelier_options_alter_utilisateur_options_and_more'),
        ('atelier', '0003_remove_rendezvous_confirme_rendezvous_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='atelier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous_atelier', to='acceil.atelier'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous_client', to='acceil.utilisateur'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous_service', to='atelier.service'),
        ),
    ]
