# Generated by Django 5.2.3 on 2025-06-13 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atelier', '0004_alter_rendezvous_atelier_alter_rendezvous_client_and_more'),
        ('atelier', '0004_convert_service_to_foreignkey'),
    ]

    operations = [
    ]
